version: "3.9"
services:
  web:
    build: .
    command: bash -lc "python src/manage.py runserver 0.0.0.0:8000"
    ports: ["8000:8000"]
    env_file: .env
    volumes:
      - .:/app
    depends_on: [db]
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wis
      POSTGRES_USER: wis
      POSTGRES_PASSWORD: wis
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
